2024-10-14 12:51:36,959 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/processamentoCSV/tipo/Viniferas
2024-10-14 12:51:39,674 - INFO - Dados recebidos da API: http://localhost:5000/processamentoCSV/tipo/Americanas
2024-10-14 12:51:43,089 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:51:47,347 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/processamentoCSV/tipo/Mesa
2024-10-14 12:51:51,569 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/processamentoCSV/tipo/Semclass
2024-10-14 12:51:55,811 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/producaoCSV
2024-10-14 12:52:00,043 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/comercializacaoCSV
2024-10-14 12:52:04,368 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/importacaoCSV/tipo/Vinhos
2024-10-14 12:52:08,612 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/importacaoCSV/tipo/Espumantes
2024-10-14 12:52:12,827 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/importacaoCSV/tipo/Frescas
2024-10-14 12:52:17,064 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/importacaoCSV/tipo/Passas
2024-10-14 12:52:21,366 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/importacaoCSV/tipo/Suco
2024-10-14 12:52:25,580 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/exportacaoCSV/tipo/Vinho
2024-10-14 12:52:29,802 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/exportacaoCSV/tipo/Espumantes
2024-10-14 12:52:34,042 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/exportacaoCSV/tipo/Uva
2024-10-14 12:52:38,256 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/exportacaoCSV/tipo/Suco
2024-10-14 12:54:34,697 - INFO - Dados recebidos da API: http://localhost:5000/processamentoCSV/tipo/Viniferas
2024-10-14 12:54:37,664 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:54:39,802 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:54:43,060 - INFO - Dados recebidos da API: http://localhost:5000/processamentoCSV/tipo/Americanas
2024-10-14 12:54:45,115 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:54:47,229 - INFO - Dados recebidos da API: http://localhost:5000/processamentoCSV/tipo/Mesa
2024-10-14 12:54:49,271 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:54:52,470 - INFO - Dados recebidos da API: http://localhost:5000/processamentoCSV/tipo/Semclass
2024-10-14 12:54:54,534 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:54:57,775 - INFO - Dados recebidos da API: http://localhost:5000/producaoCSV
2024-10-14 12:54:59,901 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:02,020 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:04,151 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:06,266 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:08,475 - INFO - Dados recebidos da API: http://localhost:5000/comercializacaoCSV
2024-10-14 12:55:10,563 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:12,685 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:14,800 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:16,901 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:19,043 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:21,153 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:23,251 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:25,356 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:29,577 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/importacaoCSV/tipo/Vinhos
2024-10-14 12:55:32,818 - INFO - Dados recebidos da API: http://localhost:5000/importacaoCSV/tipo/Espumantes
2024-10-14 12:55:34,964 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:37,658 - INFO - Dados recebidos da API: http://localhost:5000/importacaoCSV/tipo/Frescas
2024-10-14 12:55:39,819 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:42,004 - INFO - Dados recebidos da API: http://localhost:5000/importacaoCSV/tipo/Passas
2024-10-14 12:55:44,134 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:48,586 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/importacaoCSV/tipo/Suco
2024-10-14 12:55:50,854 - INFO - Dados recebidos da API: http://localhost:5000/exportacaoCSV/tipo/Vinho
2024-10-14 12:55:53,010 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2024-10-14 12:55:57,221 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/exportacaoCSV/tipo/Espumantes
2024-10-14 12:56:01,498 - ERROR - Erro: Status Code 500 ao acessar http://localhost:5000/exportacaoCSV/tipo/Uva
2024-10-14 12:56:04,282 - INFO - Dados recebidos da API: http://localhost:5000/exportacaoCSV/tipo/Suco
2024-10-14 12:56:06,449 - ERROR - Erro ao salvar arquivo no S3: Unable to locate credentials
Traceback (most recent call last):
  File "C:\Users\Felipe\PycharmProjects\FIAP-FASE-01\aws_bucket.py", line 67, in save_to_s3
    s3.put_object(Bucket=bucket_name, Key=file_key, Body=buffer.getvalue())
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\signers.py", line 197, in sign
    auth.add_auth(request)
  File "C:\Users\Felipe\anaconda3\envs\ml_fiap\Lib\site-packages\botocore\auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
